version: '3.9'
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/myapp
    # env_file:
    #   - .env
    ports:
      - 8000:8000
    command: sleep infinity

  rabbitmq:
    image: rabbitmq:management
    # env_file:
    #   - .env
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # RabbitMQ management console

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A event_email_system worker -E -l info
    # env_file:
    #   - .env
    volumes:
      - .:/myapp
    depends_on:
      - rabbitmq

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A event_email_system beat -l info
    volumes:
      - .:/myapp
    depends_on:
      - rabbitmq

